/**
* This file was automatically generated at 2021-10-05T01:42:45.120Z.
* It should not be committed to git, and you shouldn't make any changes to it.
*/

import { DocumentType } from '@typegoose/typegoose';

import { Auth as AuthSchema } from '../schemas/typegoose/Auth.schema';
import { CompanyAdvisor as CompanyAdvisorSchema } from '../schemas/typegoose/CompanyAdvisor.schema';
import { CompanyAdvisorAssignmentHistory as CompanyAdvisorAssignmentHistorySchema } from '../schemas/typegoose/CompanyAdvisorAssignmentHistory.schema';
import { CompanyInsurancePlan as CompanyInsurancePlanSchema } from '../schemas/typegoose/CompanyInsurancePlan.schema';
import { CompanyMilestone as CompanyMilestoneSchema } from '../schemas/typegoose/CompanyMilestone.schema';
import { CompanyScore as CompanyScoreSchema } from '../schemas/typegoose/CompanyScore.schema';
import { DocumentTemplate as DocumentTemplateSchema } from '../schemas/typegoose/DocumentTemplate.schema';
import { InsuranceCarrier as InsuranceCarrierSchema } from '../schemas/typegoose/InsuranceCarrier.schema';
import { LeadForm as LeadFormSchema } from '../schemas/typegoose/LeadForm.schema';
import { Locale as LocaleSchema } from '../schemas/typegoose/Locale.schema';
import { PolicyBundle as PolicyBundleSchema } from '../schemas/typegoose/PolicyBundle.schema';
import { PolicyThread as PolicyThreadSchema } from '../schemas/typegoose/PolicyThread.schema';
import { SystemAudit as SystemAuditSchema } from '../schemas/typegoose/SystemAudit.schema';
import { WorkflowResult as WorkflowResultSchema } from '../schemas/typegoose/WorkflowResult.schema';

export type Auth = DocumentType<AuthSchema>;
export type CompanyAdvisor = DocumentType<CompanyAdvisorSchema>;
export type CompanyAdvisorAssignmentHistory = DocumentType<CompanyAdvisorAssignmentHistorySchema>;
export type CompanyInsurancePlan = DocumentType<CompanyInsurancePlanSchema>;
export type CompanyMilestone = DocumentType<CompanyMilestoneSchema>;
export type CompanyScore = DocumentType<CompanyScoreSchema>;
export type DocumentTemplate = DocumentType<DocumentTemplateSchema>;
export type InsuranceCarrier = DocumentType<InsuranceCarrierSchema>;
export type LeadForm = DocumentType<LeadFormSchema>;
export type Locale = DocumentType<LocaleSchema>;
export type PolicyBundle = DocumentType<PolicyBundleSchema>;
export type PolicyThread = DocumentType<PolicyThreadSchema>;
export type SystemAudit = DocumentType<SystemAuditSchema>;
export type WorkflowResult = DocumentType<WorkflowResultSchema>;

export type Acknowledgement = any;
export type ActionItem = any;
export type CalendarEvent = any;
export type Cancellation = any;
export type CompanyOverview = any;
export type Company = any;
export type ConsumableToken = any;
export type Configuration = any;
export type Conversation = any;
export type Document = any;
export type Emergency = any;
export type EmployeeNote = any;
export type EmployeeReview = any;
export type Event = any;
export type Feed = any;
export type File = any;
export type Filestack = any;
export type Folder = any;
export type GoogleWatchChannel = any;
export type ModelLog = any;
export type Node = any;
export type Note = any;
export type PartnerUser = any;
export type Pip = any;
export type Policy = any;
export type Qna = any;
export type Question = any;
export type ReportCard = any;
export type Report = any;
export type Resignation = any;
export type Signature = any;
export type Step = any;
export type StripeEvent = any;
export type Ticket = any;
export type Termination = any;
export type Token = any;
export type Tree = any;
export type Unsubscribe = any;
export type UserProfile = any;
export type User = any;
export type Verbalwarning = any;
export type Version = any;
export type VonageCall = any;
export type Writtenwarning = any;
export type DuplicateCompany = any;

export type AcknowledgeExpectationEvent = any;
export type AcknowledgementCancellationEvent = any;
export type AcknowledgementNotificationEvent = any;
export type ActivatedEmployeeEvent = any;
export type AddedEmployeesEvent = any;
export type ApprovalApprovedEvent = any;
export type ApprovalDeniedEvent = any;
export type ApprovalRequestEvent = any;
export type AssignedAdvisorRoleEvent = any;
export type AssignedAdvisorEvent = any;
export type AssignedSalesEvent = any;
export type BciPageViewEvent = any;
export type CancelSubscriptionEvent = any;
export type CapCreatedEvent = any;
export type CompletedResignationCreatedEvent = any;
export type CompletedTerminationCreatedEvent = any;
export type CustomerRescheduledOverviewCallEvent = any;
export type CustomerScheduledGeneralCallEvent = any;
export type CustomerScheduledHrAuditCallEvent = any;
export type CustomerScheduledInitialCallEvent = any;
export type CustomerScheduledOverviewCallEvent = any;
export type CustomerScheduledPlatformCallEvent = any;
export type CustomerTicketCreatedEvent = any;
export type EmployeeSelfSignupEvent = any;
export type EmployeesAddedEvent = any;
export type HandbookCompletedEvent = any;
export type HandbookStartedEvent = any;
export type HrAuditCompleteEvent = any;
export type ImmediateCallRequestedEvent = any;
export type InitialCallCompleteEvent = any;
export type InsuranceEmailOutreachEvent = any;
export type InsuranceInterestEvent = any;
export type LoggedInEvent = any;
export type NewEmployeeWelcomeEvent = any;
export type NewLeadEvent = any;
export type NewSubscriptionEvent = any;
export type NotifyCapSignatureRequestEvent = any;
export type OnboardingInProgressEvent = any;
export type OnlineOfferSelfSignupEvent = any;
export type OverviewCallCanceledEvent = any;
export type OverviewCallCompleteEvent = any;
export type OverviewCallNoShowEvent = any;
export type OwnerActivatedAccountEvent = any;
export type PaymentFailureEvent = any;
export type PersonaCreatedEvent = any;
export type PlatformTrainingCallActivatedEvent = any;
export type PlatformTrainingCallCompleteEvent = any;
export type PoliciesSentToStaffEvent = any;
export type PolicyApprovalRequestEvent = any;
export type PolicyApprovalEvent = any;
export type PolicyCompletedEvent = any;
export type PolicyDeclineEvent = any;
export type PolicyImplementedEvent = any;
export type PolicyPassedQAEvent = any;
export type PolicyReminderSentEvent = any;
export type PolicySignedEvent = any;
export type ResendActivationEvent = any;
export type ResolvedCancellationEvent = any;
export type SalesLeadActiveEvent = any;
export type SalesNotQualifiedEvent = any;
export type SalesNurtureEvent = any;
export type SalesQualifiedEvent = any;
export type SelfSignupEvent = any;
export type SendSalesHrAuditScoreEvent = any;
export type TerminationCreatedEvent = any;
export type TerminationInProgressEvent = any;
export type UserProfileUpdatedEvent = any;
export type UserTokenUsedEvent = any;
export type UserUpdatePasswordEvent = any;

export type CalendlyConfiguration = any;
export type CancellationReasonsConfiguration = any;
export type DefaultAdvisorConfiguration = any;
export type DefaultChatOnlyConfiguration = any;
export type DefaultDuplicateCalculationConfiguration = any;
export type DefaultInsuranceAgentConfiguration = any;
export type DefaultOnboardingConfiguration = any;
export type DefaultRequestTimeConfiguration = any;
export type DefaultSalesConfiguration = any;
export type DefaultTodosConfiguration = any;
export type NewHireNoticeConfiguration = any;
export type NowcertsConfiguration = any;
export type PandaDocConfiguration = any;
export type RehireConfiguration = any;
export type SalesforceConfiguration = any;
export type SystemConfiguration = any;
export type VonageConfiguration = any;

