/**
* This file was automatically generated at 2021-10-05T01:42:45.120Z.
* It should not be committed to git, and you shouldn't make any changes to it.
*/

import * as mongoose from 'mongoose';
import { ReturnModelType } from '@typegoose/typegoose';

import {Auth as AuthSchema} from '../schemas/typegoose/Auth.schema';
import {CompanyAdvisor as CompanyAdvisorSchema} from '../schemas/typegoose/CompanyAdvisor.schema';
import {CompanyAdvisorAssignmentHistory as CompanyAdvisorAssignmentHistorySchema} from '../schemas/typegoose/CompanyAdvisorAssignmentHistory.schema';
import {CompanyInsurancePlan as CompanyInsurancePlanSchema} from '../schemas/typegoose/CompanyInsurancePlan.schema';
import {CompanyMilestone as CompanyMilestoneSchema} from '../schemas/typegoose/CompanyMilestone.schema';
import {CompanyScore as CompanyScoreSchema} from '../schemas/typegoose/CompanyScore.schema';
import {DocumentTemplate as DocumentTemplateSchema} from '../schemas/typegoose/DocumentTemplate.schema';
import {InsuranceCarrier as InsuranceCarrierSchema} from '../schemas/typegoose/InsuranceCarrier.schema';
import {LeadForm as LeadFormSchema} from '../schemas/typegoose/LeadForm.schema';
import {Locale as LocaleSchema} from '../schemas/typegoose/Locale.schema';
import {PolicyBundle as PolicyBundleSchema} from '../schemas/typegoose/PolicyBundle.schema';
import {PolicyThread as PolicyThreadSchema} from '../schemas/typegoose/PolicyThread.schema';
import {SystemAudit as SystemAuditSchema} from '../schemas/typegoose/SystemAudit.schema';
import {WorkflowResult as WorkflowResultSchema} from '../schemas/typegoose/WorkflowResult.schema';

export type Auth = ReturnModelType<typeof AuthSchema>;
export type CompanyAdvisor = ReturnModelType<typeof CompanyAdvisorSchema>;
export type CompanyAdvisorAssignmentHistory = ReturnModelType<typeof CompanyAdvisorAssignmentHistorySchema>;
export type CompanyInsurancePlan = ReturnModelType<typeof CompanyInsurancePlanSchema>;
export type CompanyMilestone = ReturnModelType<typeof CompanyMilestoneSchema>;
export type CompanyScore = ReturnModelType<typeof CompanyScoreSchema>;
export type DocumentTemplate = ReturnModelType<typeof DocumentTemplateSchema>;
export type InsuranceCarrier = ReturnModelType<typeof InsuranceCarrierSchema>;
export type LeadForm = ReturnModelType<typeof LeadFormSchema>;
export type Locale = ReturnModelType<typeof LocaleSchema>;
export type PolicyBundle = ReturnModelType<typeof PolicyBundleSchema>;
export type PolicyThread = ReturnModelType<typeof PolicyThreadSchema>;
export type SystemAudit = ReturnModelType<typeof SystemAuditSchema>;
export type WorkflowResult = ReturnModelType<typeof WorkflowResultSchema>;

export type Acknowledgement = mongoose.Model<any>;
export type ActionItem = mongoose.Model<any>;
export type CalendarEvent = mongoose.Model<any>;
export type Cancellation = mongoose.Model<any>;
export type CompanyOverview = mongoose.Model<any>;
export type Company = mongoose.Model<any>;
export type ConsumableToken = mongoose.Model<any>;
export type Configuration = mongoose.Model<any>;
export type Conversation = mongoose.Model<any>;
export type Document = mongoose.Model<any>;
export type Emergency = mongoose.Model<any>;
export type EmployeeNote = mongoose.Model<any>;
export type EmployeeReview = mongoose.Model<any>;
export type Event = mongoose.Model<any>;
export type Feed = mongoose.Model<any>;
export type File = mongoose.Model<any>;
export type Filestack = mongoose.Model<any>;
export type Folder = mongoose.Model<any>;
export type GoogleWatchChannel = mongoose.Model<any>;
export type ModelLog = mongoose.Model<any>;
export type Node = mongoose.Model<any>;
export type Note = mongoose.Model<any>;
export type PartnerUser = mongoose.Model<any>;
export type Pip = mongoose.Model<any>;
export type Policy = mongoose.Model<any>;
export type Qna = mongoose.Model<any>;
export type Question = mongoose.Model<any>;
export type ReportCard = mongoose.Model<any>;
export type Report = mongoose.Model<any>;
export type Resignation = mongoose.Model<any>;
export type Signature = mongoose.Model<any>;
export type Step = mongoose.Model<any>;
export type StripeEvent = mongoose.Model<any>;
export type Ticket = mongoose.Model<any>;
export type Termination = mongoose.Model<any>;
export type Token = mongoose.Model<any>;
export type Tree = mongoose.Model<any>;
export type Unsubscribe = mongoose.Model<any>;
export type UserProfile = mongoose.Model<any>;
export type User = mongoose.Model<any>;
export type Verbalwarning = mongoose.Model<any>;
export type Version = mongoose.Model<any>;
export type VonageCall = mongoose.Model<any>;
export type Writtenwarning = mongoose.Model<any>;
export type DuplicateCompany = mongoose.Model<any>;

export type AcknowledgeExpectationEvent = mongoose.Model<any>;
export type AcknowledgementCancellationEvent = mongoose.Model<any>;
export type AcknowledgementNotificationEvent = mongoose.Model<any>;
export type ActivatedEmployeeEvent = mongoose.Model<any>;
export type AddedEmployeesEvent = mongoose.Model<any>;
export type ApprovalApprovedEvent = mongoose.Model<any>;
export type ApprovalDeniedEvent = mongoose.Model<any>;
export type ApprovalRequestEvent = mongoose.Model<any>;
export type AssignedAdvisorRoleEvent = mongoose.Model<any>;
export type AssignedAdvisorEvent = mongoose.Model<any>;
export type AssignedSalesEvent = mongoose.Model<any>;
export type BciPageViewEvent = mongoose.Model<any>;
export type CancelSubscriptionEvent = mongoose.Model<any>;
export type CapCreatedEvent = mongoose.Model<any>;
export type CompletedResignationCreatedEvent = mongoose.Model<any>;
export type CompletedTerminationCreatedEvent = mongoose.Model<any>;
export type CustomerRescheduledOverviewCallEvent = mongoose.Model<any>;
export type CustomerScheduledGeneralCallEvent = mongoose.Model<any>;
export type CustomerScheduledHrAuditCallEvent = mongoose.Model<any>;
export type CustomerScheduledInitialCallEvent = mongoose.Model<any>;
export type CustomerScheduledOverviewCallEvent = mongoose.Model<any>;
export type CustomerScheduledPlatformCallEvent = mongoose.Model<any>;
export type CustomerTicketCreatedEvent = mongoose.Model<any>;
export type EmployeeSelfSignupEvent = mongoose.Model<any>;
export type EmployeesAddedEvent = mongoose.Model<any>;
export type HandbookCompletedEvent = mongoose.Model<any>;
export type HandbookStartedEvent = mongoose.Model<any>;
export type HrAuditCompleteEvent = mongoose.Model<any>;
export type ImmediateCallRequestedEvent = mongoose.Model<any>;
export type InitialCallCompleteEvent = mongoose.Model<any>;
export type InsuranceEmailOutreachEvent = mongoose.Model<any>;
export type InsuranceInterestEvent = mongoose.Model<any>;
export type LoggedInEvent = mongoose.Model<any>;
export type NewEmployeeWelcomeEvent = mongoose.Model<any>;
export type NewLeadEvent = mongoose.Model<any>;
export type NewSubscriptionEvent = mongoose.Model<any>;
export type NotifyCapSignatureRequestEvent = mongoose.Model<any>;
export type OnboardingInProgressEvent = mongoose.Model<any>;
export type OnlineOfferSelfSignupEvent = mongoose.Model<any>;
export type OverviewCallCanceledEvent = mongoose.Model<any>;
export type OverviewCallCompleteEvent = mongoose.Model<any>;
export type OverviewCallNoShowEvent = mongoose.Model<any>;
export type OwnerActivatedAccountEvent = mongoose.Model<any>;
export type PaymentFailureEvent = mongoose.Model<any>;
export type PersonaCreatedEvent = mongoose.Model<any>;
export type PlatformTrainingCallActivatedEvent = mongoose.Model<any>;
export type PlatformTrainingCallCompleteEvent = mongoose.Model<any>;
export type PoliciesSentToStaffEvent = mongoose.Model<any>;
export type PolicyApprovalRequestEvent = mongoose.Model<any>;
export type PolicyApprovalEvent = mongoose.Model<any>;
export type PolicyCompletedEvent = mongoose.Model<any>;
export type PolicyDeclineEvent = mongoose.Model<any>;
export type PolicyImplementedEvent = mongoose.Model<any>;
export type PolicyPassedQAEvent = mongoose.Model<any>;
export type PolicyReminderSentEvent = mongoose.Model<any>;
export type PolicySignedEvent = mongoose.Model<any>;
export type ResendActivationEvent = mongoose.Model<any>;
export type ResolvedCancellationEvent = mongoose.Model<any>;
export type SalesLeadActiveEvent = mongoose.Model<any>;
export type SalesNotQualifiedEvent = mongoose.Model<any>;
export type SalesNurtureEvent = mongoose.Model<any>;
export type SalesQualifiedEvent = mongoose.Model<any>;
export type SelfSignupEvent = mongoose.Model<any>;
export type SendSalesHrAuditScoreEvent = mongoose.Model<any>;
export type TerminationCreatedEvent = mongoose.Model<any>;
export type TerminationInProgressEvent = mongoose.Model<any>;
export type UserProfileUpdatedEvent = mongoose.Model<any>;
export type UserTokenUsedEvent = mongoose.Model<any>;
export type UserUpdatePasswordEvent = mongoose.Model<any>;

export type CalendlyConfiguration = mongoose.Model<any>;
export type CancellationReasonsConfiguration = mongoose.Model<any>;
export type DefaultAdvisorConfiguration = mongoose.Model<any>;
export type DefaultChatOnlyConfiguration = mongoose.Model<any>;
export type DefaultDuplicateCalculationConfiguration = mongoose.Model<any>;
export type DefaultInsuranceAgentConfiguration = mongoose.Model<any>;
export type DefaultOnboardingConfiguration = mongoose.Model<any>;
export type DefaultRequestTimeConfiguration = mongoose.Model<any>;
export type DefaultSalesConfiguration = mongoose.Model<any>;
export type DefaultTodosConfiguration = mongoose.Model<any>;
export type NewHireNoticeConfiguration = mongoose.Model<any>;
export type NowcertsConfiguration = mongoose.Model<any>;
export type PandaDocConfiguration = mongoose.Model<any>;
export type RehireConfiguration = mongoose.Model<any>;
export type SalesforceConfiguration = mongoose.Model<any>;
export type SystemConfiguration = mongoose.Model<any>;
export type VonageConfiguration = mongoose.Model<any>;

